# Default values for epirust.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config: "mumbai_ward_25.json"

multiengineSim: true

engine:
  fullname: "mumbai-ward-engine-25-1"
  spec:
    completions: 24
    parallelism: 24
  image:
    repository: "sapanakale/epirust-engine"
    tag: "commute-latest-10"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "1000m"
      memory: "4Gi"
    limits:
      cpu: "1000m"
      memory: "4Gi"
  env:
    EPI_KAFKA_URL: "kafka-cp-kafka:9092"
    RUST_LOG: debug
    RUST_BACKTRACE: full
  volumes:
    name: "epirust-storage"
    claimName: "epirust-claim"
  volumeMounts:
    output:
      subPath: "epirust/output/mumbai_multi_engine/25/run_1"
    config:
      subPath: "epirust/config"

orchestrator:
  fullname: "mumbai-ward-orchestrator-25-1"
  image:
    repository: "sapanakale/epirust-orchestrator"
    pullPolicy: IfNotPresent
    tag: "commute-latest-8"
  resources:
    requests:
      cpu: "1000m"
      memory: "4Gi"
    limits:
      cpu: "1000m"
      memory: "4Gi"
  env:
    EPI_KAFKA_URL: "kafka-cp-kafka:9092"
    RUST_LOG: debug
    RUST_BACKTRACE: full
  volumes:
    name: "epirust-storage"
    claimName: "epirust-claim"
  volumeMounts:
    config:
      mountPath: "config"
      subPath: "epirust/config"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: NotIn
#              values:
#                - k8s-node2.e4r.thoughtworks.net



