apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: epirust-local-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: k8s-node4.e4r.thoughtworks.net
    path: /nfs_data
    readOnly: no
