apiVersion: v1
kind: PersistentVolume
metadata:
  name: epirust-volume
  labels:
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    # replace <dns-name> it with your efs server
    server: <dns-name>
    path: /
    readOnly: no
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard,timeo=600
    - retrans=2
    - noresvport

