# Default values for epirust.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Add the name of config file for which you want to run the simulations
config: "pune_ward_wise.json"

# Set it as "true" if you are running simulations for distributed mode (multi-engine) and
# "false" for serial, parallel implementation (single engine).
multiengineSim: true

engine:
  fullname: "pune-engines-1"

  # Specify the number of threads for parallel operation according to the total number of agents and resources per engine
  number_of_threads: 1

  spec:
    # Specify the number of engines for which you are running simulation
    completions: 15
    parallelism: 15

  image:
    # Replace it with your image repository and tag for engine
    repository: "epirust-engine"
    tag: "latest"
    pullPolicy: Always

  resources:
    # Update the resources for engine according to need
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  env:
    # Replace with your kafka service url
    EPI_KAFKA_URL: "kafka-cp-kafka:9092"
    # Replace with jaeger host and port for tracing
    OTEL_EXPORTER_JAEGER_AGENT_PORT: "6831"
    OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"
    EPI_OUTPUT_DIR: "/home/nonroot/app/output"

    RUST_LOG: info
    RUST_BACKTRACE: full

orchestrator:
  fullname: "pune-orchestrator-1"

  # Replace it with your image repository and tag for orchestrator
  image:
    repository: "epirust-orchestrator"
    pullPolicy: Always
    tag: "latest"

  # Update the resources for orchestrator according to need
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  env:
    # Replace with your kafka service url
    EPI_KAFKA_URL: "kafka-cp-kafka:9092"

    RUST_LOG: info
    RUST_BACKTRACE: full

#Update the storage related details
storage:
  # Update with your volume name and claim name
  volumes:
    name: "epirust-storage"
    claimName: "epirust-claim"

  # Update the sub paths for output and config
  volumeMounts:
    config:
      mountPath: "/home/nonroot/app/config"
      subPath: "epirust/config"
    output:
      mountPath: "/home/nonroot/app/output"
      subPath: "epirust/output/100k_100"

# Security settings for epirust engine and orchestrator pods
securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

nodeSelector: {}

tolerations: []

affinity: {}