{{ if .Values.multiengineSim }}
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-topics
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: delete-topics
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install-job
          image: "confluentinc/cp-enterprise-kafka:6.1.0"
          command: ["/bin/bash","-c", "
          kafka-topics --delete --bootstrap-server kafka-cp-kafka:9092 --topic simulation_requests --if-exists &&
          kafka-topics --delete --bootstrap-server kafka-cp-kafka:9092 --topic counts_updated --if-exists &&
          kafka-topics --delete --bootstrap-server kafka-cp-kafka:9092 --topic ticks --if-exists &&
          kafka-topics --delete --bootstrap-server kafka-cp-kafka:9092 --topic ticks_ack --if-exists &&
          kafka-topics --delete --bootstrap-server kafka-cp-kafka:9092 --topic commute --if-exists &&
          kafka-topics --delete --bootstrap-server kafka-cp-kafka:9092 --topic migration --if-exists &&
          kafka-topics --delete --bootstrap-server kafka-cp-kafka:9092 --topic travels --if-exists &&
          kafka-topics --create --bootstrap-server kafka-cp-kafka:9092 --topic simulation_requests --partitions 1 --replication-factor 1 --if-not-exists &&
          kafka-topics --create --bootstrap-server kafka-cp-kafka:9092 --topic counts_updated  --partitions 1 --replication-factor 1 --if-not-exists &&
          kafka-topics --create --bootstrap-server kafka-cp-kafka:9092 --topic ticks --partitions 1 --replication-factor 1 --if-not-exists &&
          kafka-topics --create --bootstrap-server kafka-cp-kafka:9092 --topic ticks_ack --partitions 1 --replication-factor 1 --if-not-exists &&
          kafka-topics --create --bootstrap-server kafka-cp-kafka:9092 --topic commute --partitions 1 --replication-factor 1 --if-not-exists &&
          kafka-topics --create --bootstrap-server kafka-cp-kafka:9092 --topic migration --partitions 1 --replication-factor 1 --if-not-exists &&
          kafka-topics --create --bootstrap-server kafka-cp-kafka:9092 --topic travels --partitions 1 --replication-factor 1 --if-not-exists &&
          kafka-topics --list --bootstrap-server kafka-cp-kafka:9092"]
{{ end }}
