name: cargo-audit
on:
  push:
    branches:
      - dev
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  paradox:
    runs-on: ubuntu-latest

    steps:
      - name: rust-audit-check
        uses: actions-rs/audit-check@v1.2.0


