name: cargo-audit
on:
  push:
    branches:
      - dev


jobs:
  paradox:
    runs-on: ubuntu-latest
    steps:
#        - uses: actions/checkout@v1
#        - run: cd $GITHUB_WORKSPACE && mv engine/Cargo.toml .
#        - run: cd $GITHUB_WORKSPACE && rm -rf infra
#        - name: rust-audit-check
#          uses: actions-rs/audit-check@v1.2.0
#          with:
#            token: ${{ secrets.GITHUB_TOKEN }}

        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
            ref: ${{ github.head_ref }} // necessary for pull request workflow trigger

        - name: Trufflehog Actions Scan
          uses: edplato/trufflehog-actions-scan@v0.9l-beta

        - name: Aqua Security Trivy
          uses: aquasecurity/trivy-action@0.7.1
          with:
            image-ref: 'gcr.io/distroless/cc'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
