name: cargo-audit
on:
  push:
    branches:
      - dev
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  paradox:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
            ref: ${{ github.head_ref }} // necessary for pull request workflow trigger

        - name: Trufflehog Actions Scan
          uses: edplato/trufflehog-actions-scan@v0.9l-beta

        - name: Aqua Security Trivy
          uses: aquasecurity/trivy-action@0.7.1
          with:
            image-ref: 'gcr.io/distroless/cc'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
